name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    services:
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy
        ports:
          - 8474:8474
          - 21212:21212

    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.16.3"
              otp: "26.2.5.3"
          - pair:
              elixir: "1.17.3"
              otp: "27.1"
          - pair:
              elixir: "1.18.3"
              otp: "27.3"
          - pair:
              elixir: "1.19.0"
              otp: "28.1"
              lint: lint
    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Start Python API Server (Background)
      run: |
        uv run --directory test_server route_guide_server.py &
    - name: Set up Elixir
      uses: erlef/setup-beam@main
      with:
        otp-version: ${{ matrix.pair.otp }}
        elixir-version: ${{ matrix.pair.elixir }}
        version-type: strict
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - run: mix deps.get --check-locked
    - run: mix format --check-formatted
      if: ${{ matrix.pair.lint }}
    - run: mix deps.unlock --check-unused
      if: ${{ matrix.pair.lint }}
    - run: mix deps.compile
    - run: mix compile --no-optional-deps --warnings-as-errors
      if: ${{ matrix.pair.lint }}
    - run: mix dialyzer
      if: ${{ matrix.pair.lint }}
    - run: mix test --slowest 5
      if: ${{ ! matrix.pair.lint }}
    - run: mix test --slowest 5 --warnings-as-errors
      if: ${{ matrix.pair.lint }}
